### ISSUE TITLE
Wildcard/Regex Filtering for a Tag's Pattern

### ISSUE THREAD

**Issue by d4mation** [realbig/PL_PYIS_HELPSCOUT_DRIP#1]
> I keep track of a user's "status" (i.e., active, canceled, lifetime, etc.) and even a simple wildcard here would be helpful. Regex filtering might be overkill but would solve all problems.

@jrosebr1 this is a really cool idea. Would it be just a single Wildcard/Regex expression that you'd want to be able to implement? Or would you need to/want to check against multiple different ones?

**Comment by d4mation** [comment]
Actually, now that I think about it (And looking at the screenshot from #4) implementing the Regex check into the "Tag" itself would likely work the best.

**Comment by jrosebr1** [comment]
I'm not sure how you have the tag fetching and filtering now, but I was thinking of something along the lines of:

<pre>for tag in tags:
    for pattern in patterns:
        if pattern.matches(tag):
            keep_tags[tag] = true
            break</pre>
