### ISSUE TITLE
CSS bug

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_HELPSCOUT_DRIP#10]
I just noticed a CSS bug on featured vs. non-featured jobs.

Here is a link to a non-featured job:

https://jobs.pyimagesearch.com/job/public-relations-and-marketing-executive/

Notice how the background color of the job is white.

However, here is a link to a featured job:

https://jobs.pyimagesearch.com/job/python-consulting-23-python-opencv-developer/

Notice how the background color of the job is the yellow used for featured jobs on the homepage.

EDIT: As far as I know, this bug did not happen until we upgraded the WordPress plugins last week. I think it might be a problem with their latest release.

![screen shot 2017-07-26 at 10 29 07 am](https://user-images.githubusercontent.com/759645/28626545-48536f0c-71ed-11e7-863a-437763b48401.png)

**Comment by joelworsham** [comment]
Ah yes. Funny thing is the theme also colors this background with the more subtle yellow that we darkened. The class styling this must have been added recently to the single page template.

I've overriden this. All set.
