### ISSUE TITLE
Tag Filtering is not working as expected

### ISSUE THREAD

**Issue by d4mation** [realbig/PL_PYIS_HELPSCOUT_DRIP#2]
![image](https://cloud.githubusercontent.com/assets/7770631/23464357/b8c673c8-fe62-11e6-9e49-2591c1984830.png)

![image](https://cloud.githubusercontent.com/assets/7770631/23464397/d49336f4-fe62-11e6-850e-cb9d8c98b928.png)

**Comment by jrosebr1** [comment]
This is actually not a bug. I forgot to click the "Save Changes" button the first time I tested out the integration. It does indeed work when you click "Save Changes" User error on my part. Test it out to make sure, but I think you can close this.

**Comment by d4mation** [comment]
Ok, I had tested myself and I wasn't able to reproduce. Figured I'd hit some other things first before coming around to this.

Thanks for the update!
