### ISSUE TITLE
Change display of Tags on HelpScout

### ISSUE THREAD

**Issue by d4mation** [realbig/PL_PYIS_HELPSCOUT_DRIP#5]
> Using a an unordered list to render the tags takes up too much screen real-estate. Can we do something similar to the Drip dashboard where it's a "blob" of tags to save space?

**Comment by d4mation** [comment]
Drip view:

![image](https://cloud.githubusercontent.com/assets/7770631/23466179/5e3ab864-fe68-11e6-95e5-1311f1720aef.png)

**Comment by d4mation** [comment]
New HelpScout App/Widget view:

![image](https://cloud.githubusercontent.com/assets/7770631/23476406/a9256f16-fe88-11e6-8b25-86837da9e907.png)

**Comment by jrosebr1** [comment]
The new visualization looks ***awesome***!
