### ISSUE TITLE
Include lead score

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_HELPSCOUT_DRIP#7]
Drip associates a "lead score" with every subscriber (the number next to the subscriber name). Can this be pulled down from the Drip API and displayed inside HelpScout as well?

**Comment by d4mation** [comment]
Yep, that should be possible! Where are you thinking of putting it? Just above the Tags?

Something like: `Lead Score: <value>`?

**Comment by jrosebr1** [comment]
Yep, that's exactly right!

**Comment by d4mation** [comment]
If there are no (matching) Tags found, should it still check for and return a Lead Score?

**Comment by jrosebr1** [comment]
Yes, please check for lead score even if no matching tags are found.

**Comment by d4mation** [comment]
This is included in the latest release: https://github.com/realbig/PL_PYIS_HELPSCOUT_DRIP/releases/tag/v0.4.0

In our Test Drip Account, none of our Subscribers have a Lead Score and it seems there's no way to manually set one. In my case, they all returned `null`.

As far as I can tell it should work normally with actual data (I faked some real Lead Score data and it worked just fine), but let me know if it needs tweaking. 

If a Subscriber doesn't have a Lead Score, it will say so similarly to if there are no (applicable) Tags.

**Comment by jrosebr1** [comment]
Just a quick question:

Inside HelpScout do I need to delete and re-create the app to have v0.4 working?

I just loaded up HelpScout and I didn't see any lead score information.

**Comment by d4mation** [comment]
Nope, you should not have to do that. Maybe it is a caching problem on the WP Server?

That's weird that it isn't showing for you. It should either show a Lead Score, or it should show something like this:

![image](https://cloud.githubusercontent.com/assets/7770631/23668107/0d984c94-032e-11e7-92c5-6f2269c24266.png)

I just re-uploaded v0.4.0 to our testing server to make sure and it is showing for me.

**Comment by d4mation** [comment]
Just to be sure:

Does the version of the plugin that you've uploaded have the following file path?

`/wp-content/plugins/pyis-helpscout-drip/core/views/pyis-helpscout-drip-lead-score-row.php`

If it finds a Lead Score but that file doesn't exist, it could explain why it isn't properly rendering for you.

**Comment by jrosebr1** [comment]
I've tried to debug this more, but I can't seem to determine what the issue is. I'm actually using the same development server (ash) as you are to test out the plugin:

<pre>$ cd wp-content/plugins/pyis-helpscout-drip/
$ ls core/views/
pyis-helpscout-drip-tag-row.php</pre>

The code is certainly there since this is the dev server. Do I need to re-install the app on HelpScout's side?

**Comment by jrosebr1** [comment]
Discard my previous comment, I misread your filename. The `pyis-helpscout-drip-lead-score-row.php` template isn't there. For some reason I thought we were both using the same dev server (my fault). I will update and retry.

**Comment by jrosebr1** [comment]
Confirmed, the lead scoring is now working -- it was my fault for not updating the correct server. This can be closed now.
