### ISSUE TITLE
Determine which HelpScout user is loading content

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_HELPSCOUT_DRIP#9]
Nice job adding in the Drip subscriber profile link to the sidebar, it works perfectly.

I had one last question regarding this feature:

Right now I have a person on my team who answers and replies to readers inside of HelpScout. They can see the tags, which is exactly the indented functionality of this plugin. If they were to click on the subscriber link they would not be able to access the subscriber in Drip because they don't have my login credentials (which is the intended behavior).

Is there a way to _detect_ which HelpScout user is requesting the sidebar content and then _hide_ the Drip profile link from them?

This also goes back to #8. In a multi-user environment we would need to know which user was loading what content since not all users should have the same permissions.

**Comment by d4mation** [comment]
It should be possible. Here's some example JSON of what HelpScout sends to the WP server. 

We could check the First Name and/or Last Name or the User ID to determine whether to show that Link or not.

```
{  
   "ticket":{  
      "id":"ticket_id",
      "number":"ticket_number",
      "subject":"ticket_subject"
   },
   "customer":{  
      "id":"customer_id",
      "fname":"",
      "lname":"",
      "email":"customer_email",
      "emails":[  
         "customer_emails_array"
      ]
   },
   "user":{  
      "fname":"HelpScout_user_first_name",
      "lname":"HelpScout_user_last_name",
      "id":"HelpScout_user_id",
      "role":"HelpScout_user_role",
      "convRedirect":0
   },
   "mailbox":{  
      "id":"HelpScout_mailbox_id",
      "email":"HelpScout_mailbox_email"
   }
}
```

**Comment by jrosebr1** [comment]
User ID should be easiest. Let's put that as a field in the WP admin.

This should be the last update for the final release, everything else is working great.

**Comment by d4mation** [comment]
This bit of functionality has been added as `v0.5.0`.

If everything works on your end, I'll go ahead and bump it up to `v1.0.0` :+1:

https://github.com/realbig/PL_PYIS_HELPSCOUT_DRIP/releases/tag/v0.5.0

**Comment by jrosebr1** [comment]
Perfect, go ahead and bump this up to `v1.0.0`. 👍

**Comment by d4mation** [comment]
Just bumped to v1.0.0 :+1:

https://github.com/realbig/PL_PYIS_HELPSCOUT_DRIP/releases/tag/v1.0.0

**Comment by jrosebr1** [comment]
All installed and running now. Looks good.
